@claimId = 5929e58d-338d-4bc4-b37e-364fb3fe83c4

GET {{host}}/claims

###
GET {{host}}/claims/{{claimId}}

###
POST {{host}}/claims
Content-Type: application/json

{
    "claim_id": "{{claimId}}",
    "description": "Claim 8",
    "amount": 800.0,
    "status": "Accepted"
}

###
DELETE {{host}}/claims/{{claimId}}
